# Generated by Django 3.2.17 on 2023-02-12 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("bacen_code", models.CharField(max_length=6, unique=True)),
                ("image_url", models.URLField(max_length=400)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agency", models.CharField(max_length=10)),
                ("agency_digit", models.CharField(default="0", max_length=1)),
                ("account", models.CharField(max_length=10)),
                ("account_digit", models.CharField(default="X", max_length=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bank"
                    ),
                ),
            ],
            options={
                "unique_together": {("bank", "agency", "account")},
            },
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("pix_key", models.CharField(max_length=140)),
                (
                    "pix_key_type",
                    models.CharField(
                        choices=[
                            ("CPF", "CPF"),
                            ("CNPJ", "CNPJ"),
                            ("EMAIL", "E-mail"),
                            ("TELEFONE", "Telefone"),
                            ("CHAVE_ALEATORIA", "Chave Aleatória"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=250, null=True)),
                ("document", models.CharField(max_length=18)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("CNPJ", "CNPJ"), ("CPF", "CPF")],
                        default="CPF",
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALIDADO", "Validado"),
                            ("INVALIDO", "Inválido"),
                            ("RASCUNHO", "Rascunho"),
                        ],
                        default="RASCUNHO",
                        max_length=15,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bankaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
