# Generated by Django 3.2.18 on 2023-02-15 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiver",
            unique_together={("document", "pix_key", "pix_key_type")},
        ),
    ]
